//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.10 at 01:51:57 PM IST 
//


package com.hotelserver.model.search;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AgentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AgentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="agentName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="corpDeskEmail" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="navCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AgentType")
public class AgentType {

    @XmlAttribute(name = "agentName")
    protected String agentName;
    @XmlAttribute(name = "corpDeskEmail")
    protected String corpDeskEmail;
    @XmlAttribute(name = "navCode")
    protected String navCode;

    /**
     * Gets the value of the agentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentName() {
        return agentName;
    }

    /**
     * Sets the value of the agentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentName(String value) {
        this.agentName = value;
    }

    /**
     * Gets the value of the corpDeskEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorpDeskEmail() {
        return corpDeskEmail;
    }

    /**
     * Sets the value of the corpDeskEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorpDeskEmail(String value) {
        this.corpDeskEmail = value;
    }

    /**
     * Gets the value of the navCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNavCode() {
        return navCode;
    }

    /**
     * Sets the value of the navCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNavCode(String value) {
        this.navCode = value;
    }

}
