//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.13 at 11:52:17 PM IST 
//


package com.hotelserver.model.booking;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rateProvider complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rateProvider"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Supplier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SubSupplier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ProviderInfo" type="{http://www.opentravel.org/OTA/2003/05}providerInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rateProvider", propOrder = {
    "supplier",
    "subSupplier",
    "providerInfo"
})
public class RateProvider {

    @XmlElement(name = "Supplier", required = true)
    protected String supplier;
    @XmlElement(name = "SubSupplier", required = true)
    protected String subSupplier;
    @XmlElement(name = "ProviderInfo")
    protected List<ProviderInfo> providerInfo;

    /**
     * Gets the value of the supplier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * Sets the value of the supplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplier(String value) {
        this.supplier = value;
    }

    /**
     * Gets the value of the subSupplier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubSupplier() {
        return subSupplier;
    }

    /**
     * Sets the value of the subSupplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubSupplier(String value) {
        this.subSupplier = value;
    }

    /**
     * Gets the value of the providerInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the providerInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProviderInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProviderInfo }
     * 
     * 
     */
    public List<ProviderInfo> getProviderInfo() {
        if (providerInfo == null) {
            providerInfo = new ArrayList<ProviderInfo>();
        }
        return this.providerInfo;
    }

}
