//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.16 at 10:17:22 PM IST 
//


package com.hotelserver.model.dumpdata;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.jaxb.generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsHotelReviewsHotelReview_QNAME = new QName("http://www.opentravel.org/OTA/2003/05", "HotelReview");
    private final static QName _OTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsPopularityIndexesPopularityIndex_QNAME = new QName("http://www.opentravel.org/OTA/2003/05", "PopularityIndex");
    private final static QName _OTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentFacilityInfoGuestRoomsGuestRoom_QNAME = new QName("http://www.opentravel.org/OTA/2003/05", "GuestRoom");
    private final static QName _OTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsInAndAroundsInAndAround_QNAME = new QName("http://www.opentravel.org/OTA/2003/05", "InAndAround");
    private final static QName _OTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsRoomLevelAmenitiesRoomLevelAmenity_QNAME = new QName("http://www.opentravel.org/OTA/2003/05", "RoomLevelAmenity");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.jaxb.generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.HotelReviews }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.HotelReviews createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsHotelReviews() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.HotelReviews();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.AffiliationInfo }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.AffiliationInfo createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentAffiliationInfo() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.AffiliationInfo();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentHotelInfoDescriptions() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.ThemeList }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.ThemeList createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsThemeList() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.ThemeList();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.Facilities.Amenity }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.Facilities.Amenity createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsFacilitiesAmenity() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.Facilities.Amenity();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.HotelReviews.HotelReview }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.HotelReviews.HotelReview createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsHotelReviewsHotelReview() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.HotelReviews.HotelReview();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentHotelInfo() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription.ImageItems }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription.ImageItems createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentHotelInfoDescriptionsMultimediaDescriptionsMultimediaDescriptionImageItems() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription.ImageItems();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentHotelInfoDescriptionsMultimediaDescriptionsMultimediaDescription() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.RoomLevelAmenities }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.RoomLevelAmenities createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsRoomLevelAmenities() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.RoomLevelAmenities();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentHotelInfoDescriptionsMultimediaDescriptions() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.PopularityIndexes.PopularityIndex }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.PopularityIndexes.PopularityIndex createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsPopularityIndexesPopularityIndex() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.PopularityIndexes.PopularityIndex();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.ContactInfos.ContactInfo.Addresses }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.ContactInfos.ContactInfo.Addresses createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentContactInfosContactInfoAddresses() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.ContactInfos.ContactInfo.Addresses();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.Facilities }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.Facilities createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsFacilities() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.Facilities();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.Policies.Policy.PolicyInfo }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.Policies.Policy.PolicyInfo createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentPoliciesPolicyPolicyInfo() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.Policies.Policy.PolicyInfo();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.CategoryList }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.CategoryList createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsCategoryList() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.CategoryList();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Position }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Position createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentHotelInfoPosition() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Position();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.ContactInfos.ContactInfo.Addresses.Address }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.ContactInfos.ContactInfo.Addresses.Address createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentContactInfosContactInfoAddressesAddress() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.ContactInfos.ContactInfo.Addresses.Address();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.Policies.Policy }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.Policies.Policy createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentPoliciesPolicy() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.Policies.Policy();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.AffiliationInfo.DistribSystems.DistribSystem }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.AffiliationInfo.DistribSystems.DistribSystem createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentAffiliationInfoDistribSystemsDistribSystem() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.AffiliationInfo.DistribSystems.DistribSystem();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription.CloudinaryImageItems.ImageItem }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription.CloudinaryImageItems.ImageItem createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentHotelInfoDescriptionsMultimediaDescriptionsMultimediaDescriptionCloudinaryImageItemsImageItem() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription.CloudinaryImageItems.ImageItem();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription.CloudinaryImageItems.ImageItem.ImageFormat }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription.CloudinaryImageItems.ImageItem.ImageFormat createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentHotelInfoDescriptionsMultimediaDescriptionsMultimediaDescriptionCloudinaryImageItemsImageItemImageFormat() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription.CloudinaryImageItems.ImageItem.ImageFormat();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.AffiliationInfo.DistribSystems }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.AffiliationInfo.DistribSystems createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentAffiliationInfoDistribSystems() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.AffiliationInfo.DistribSystems();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription.CloudinaryImageItems }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription.CloudinaryImageItems createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentHotelInfoDescriptionsMultimediaDescriptionsMultimediaDescriptionCloudinaryImageItems() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription.CloudinaryImageItems();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.Policies }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.Policies createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentPolicies() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.Policies();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.InAndArounds.InAndAround }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.InAndArounds.InAndAround createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsInAndAroundsInAndAround() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.InAndArounds.InAndAround();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.InAndArounds }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.InAndArounds createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsInAndArounds() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.InAndArounds();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.FacilityInfo }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.FacilityInfo createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentFacilityInfo() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.FacilityInfo();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription.ImageItems.ImageItem }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription.ImageItems.ImageItem createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentHotelInfoDescriptionsMultimediaDescriptionsMultimediaDescriptionImageItemsImageItem() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription.ImageItems.ImageItem();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription.ImageItems.ImageItem.ImageFormat }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription.ImageItems.ImageItem.ImageFormat createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentHotelInfoDescriptionsMultimediaDescriptionsMultimediaDescriptionImageItemsImageItemImageFormat() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.HotelInfo.Descriptions.MultimediaDescriptions.MultimediaDescription.ImageItems.ImageItem.ImageFormat();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensions() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.FacilityInfo.GuestRooms.GuestRoom }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.FacilityInfo.GuestRooms.GuestRoom createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentFacilityInfoGuestRoomsGuestRoom() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.FacilityInfo.GuestRooms.GuestRoom();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents createOTAHotelDescriptiveInfoRSHotelDescriptiveContents() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS }
     * 
     */
    public OTAHotelDescriptiveInfoRS createOTAHotelDescriptiveInfoRS() {
        return new OTAHotelDescriptiveInfoRS();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.PopularityIndexes }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.PopularityIndexes createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsPopularityIndexes() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.PopularityIndexes();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.RoomLevelAmenities.RoomLevelAmenity }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.RoomLevelAmenities.RoomLevelAmenity createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsRoomLevelAmenitiesRoomLevelAmenity() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.RoomLevelAmenities.RoomLevelAmenity();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContent() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.ContactInfos }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.ContactInfos createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentContactInfos() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.ContactInfos();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.FacilityInfo.GuestRooms }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.FacilityInfo.GuestRooms createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentFacilityInfoGuestRooms() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.FacilityInfo.GuestRooms();
    }

    /**
     * Create an instance of {@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.ContactInfos.ContactInfo }
     * 
     */
    public OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.ContactInfos.ContactInfo createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentContactInfosContactInfo() {
        return new OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.ContactInfos.ContactInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.HotelReviews.HotelReview }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentravel.org/OTA/2003/05", name = "HotelReview", scope = OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.HotelReviews.class)
    public JAXBElement<OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.HotelReviews.HotelReview> createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsHotelReviewsHotelReview(OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.HotelReviews.HotelReview value) {
        return new JAXBElement<OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.HotelReviews.HotelReview>(_OTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsHotelReviewsHotelReview_QNAME, OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.HotelReviews.HotelReview.class, OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.HotelReviews.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.PopularityIndexes.PopularityIndex }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentravel.org/OTA/2003/05", name = "PopularityIndex", scope = OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.PopularityIndexes.class)
    public JAXBElement<OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.PopularityIndexes.PopularityIndex> createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsPopularityIndexesPopularityIndex(OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.PopularityIndexes.PopularityIndex value) {
        return new JAXBElement<OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.PopularityIndexes.PopularityIndex>(_OTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsPopularityIndexesPopularityIndex_QNAME, OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.PopularityIndexes.PopularityIndex.class, OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.PopularityIndexes.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.FacilityInfo.GuestRooms.GuestRoom }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentravel.org/OTA/2003/05", name = "GuestRoom", scope = OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.FacilityInfo.GuestRooms.class)
    public JAXBElement<OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.FacilityInfo.GuestRooms.GuestRoom> createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentFacilityInfoGuestRoomsGuestRoom(OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.FacilityInfo.GuestRooms.GuestRoom value) {
        return new JAXBElement<OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.FacilityInfo.GuestRooms.GuestRoom>(_OTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentFacilityInfoGuestRoomsGuestRoom_QNAME, OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.FacilityInfo.GuestRooms.GuestRoom.class, OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.FacilityInfo.GuestRooms.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.InAndArounds.InAndAround }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentravel.org/OTA/2003/05", name = "InAndAround", scope = OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.InAndArounds.class)
    public JAXBElement<OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.InAndArounds.InAndAround> createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsInAndAroundsInAndAround(OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.InAndArounds.InAndAround value) {
        return new JAXBElement<OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.InAndArounds.InAndAround>(_OTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsInAndAroundsInAndAround_QNAME, OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.InAndArounds.InAndAround.class, OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.InAndArounds.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.RoomLevelAmenities.RoomLevelAmenity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentravel.org/OTA/2003/05", name = "RoomLevelAmenity", scope = OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.RoomLevelAmenities.class)
    public JAXBElement<OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.RoomLevelAmenities.RoomLevelAmenity> createOTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsRoomLevelAmenitiesRoomLevelAmenity(OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.RoomLevelAmenities.RoomLevelAmenity value) {
        return new JAXBElement<OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.RoomLevelAmenities.RoomLevelAmenity>(_OTAHotelDescriptiveInfoRSHotelDescriptiveContentsHotelDescriptiveContentTPAExtensionsRoomLevelAmenitiesRoomLevelAmenity_QNAME, OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.RoomLevelAmenities.RoomLevelAmenity.class, OTAHotelDescriptiveInfoRS.HotelDescriptiveContents.HotelDescriptiveContent.TPAExtensions.RoomLevelAmenities.class, value);
    }

}
