//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.10 at 01:51:57 PM IST 
//


package com.hotelserver.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Breakdown complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Breakdown"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="excluded" type="{http://www.opentravel.org/OTA/2003/05}Charges" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="included" type="{http://www.opentravel.org/OTA/2003/05}Charges" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Breakdown", propOrder = {
    "excluded",
    "included"
})
public class Breakdown {

    @XmlElement(nillable = true)
    protected List<Charges> excluded;
    @XmlElement(nillable = true)
    protected List<Charges> included;

    /**
     * Gets the value of the excluded property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the excluded property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExcluded().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Charges }
     * 
     * 
     */
    public List<Charges> getExcluded() {
        if (excluded == null) {
            excluded = new ArrayList<Charges>();
        }
        return this.excluded;
    }

    /**
     * Gets the value of the included property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the included property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncluded().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Charges }
     * 
     * 
     */
    public List<Charges> getIncluded() {
        if (included == null) {
            included = new ArrayList<Charges>();
        }
        return this.included;
    }

}
